[package]
name = "dpp"
edition = "2024.beta"
authors = ["Valerio Mellini (valerio@kchain.solutions)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
dpp = "0x0"

[dev-addresses]
